services:
    server:
        build:
            context: .
        ports:
            - 8080:8080
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/build
        environment:
            - POSTGRES_URL=jdbc:postgresql://db:5432/finboostplus
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finboostplus
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=1234
    db:
        image: postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=finboostplus
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
        ports:
            - 5432:5432
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'postgres']
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data:
